# Generated by Django 5.1.1 on 2024-10-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adquirentes', '0001_initial'),
        ('clients', '0007_alter_clients_created_by_alter_clients_group_and_more'),
        ('payments', '0004_paymentstatus_salestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('refo_id', models.IntegerField()),
                ('estabelecimento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_pagamento', models.DateField()),
                ('data_prevista_pagamento', models.DateField()),
                ('data_venda', models.DateField()),
                ('autorizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('nsu', models.CharField(blank=True, max_length=50, null=True)),
                ('id_transacao', models.CharField(blank=True, max_length=50, null=True)),
                ('parcela', models.IntegerField(default=0)),
                ('total_parcelas', models.IntegerField(default=0)),
                ('resumo_venda', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('outras_despesas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idt_antecipacao', models.BooleanField(default=False)),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('conta', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_loja', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('divergencias', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_liquido_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_ajuste', models.CharField(blank=True, max_length=100, null=True)),
                ('conta_adquirente', models.BooleanField(blank=True, null=True)),
                ('taxa_antecipacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taxa_antecipacao_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_taxa_antecipacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_taxa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tem_conciliacao_bancaria', models.BooleanField(default=False)),
                ('cartao', models.CharField(blank=True, max_length=50, null=True)),
                ('adquirente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='adquirentes.acquirer')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.clients')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.paymentstatus')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.modality')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.product')),
                ('transactiontype', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='payments.transactiontype')),
            ],
        ),
        migrations.DeleteModel(
            name='SaleStatus',
        ),
    ]
