# Generated by Django 5.1.1 on 2024-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_received_delete_salestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
