# Generated by Django 5.1.1 on 2024-10-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client',
        ),
    ]
