# Generated by Django 5.1.1 on 2024-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_modality_code_alter_modality_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='data_prevista_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='data_venda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
