# Generated by Django 5.1.1 on 2024-10-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_typecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='payments.typecard'),
        ),
    ]
