# Generated by Django 5.1.1 on 2024-10-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_servicospagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='divergencias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='motivo_ajuste',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='observacao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='resumo_venda',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
