# Generated by Django 5.1.1 on 2024-11-25 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_received_payments_re_client__2fdab1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_update', models.JSONField()),
                ('after_update', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='payments.received')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
