# Generated by Django 5.1.1 on 2024-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adquirentes', '0001_initial'),
        ('clients', '0007_alter_clients_created_by_alter_clients_group_and_more'),
        ('payments', '0016_receivedupdatelog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='received',
            constraint=models.UniqueConstraint(fields=('id', 'client'), name='unique_id_client'),
        ),
    ]
