# Generated by Django 5.1.1 on 2024-12-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_received_unique_id_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='id_received',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
