# Generated by Django 5.1.1 on 2024-12-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_received_unique_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
