# Generated by Django 5.1.1 on 2024-12-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_received_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='received',
            name='unique_id_client',
        ),
        migrations.AlterField(
            model_name='received',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
