# Generated by Django 5.1.1 on 2024-10-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_sharedlink_action_01_sharedlink_action_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
