# Generated by Django 5.1.1 on 2024-10-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_logexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='download_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
