# Generated by Django 5.1.1 on 2024-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_sharedlink_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedlink',
            name='client',
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='client',
            field=models.JSONField(default=list, blank=True, null=True),
        ),
    ]

