# Generated by Django 5.1.1 on 2024-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_remove_logexport_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='logexport',
            name='client',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
