# Generated by Django 5.1.1 on 2024-10-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_last_end_date_customuser_last_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_client_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
