# Generated by Django 5.1.1 on 2024-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verify_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify_number_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
