# Generated by Django 5.1.1 on 2024-11-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_verify_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_client_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_client_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
