# Generated by Django 5.1.1 on 2024-11-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_last_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_client_ids',
            new_name='last_client_id',
        ),
    ]
