# Generated by Django 5.1.1 on 2024-10-15 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_groups_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=255)),
                ('fantasy_name', models.CharField(max_length=255)),
                ('direction_street', models.CharField(max_length=255)),
                ('direction_street_number', models.CharField(max_length=10)),
                ('direction_street_complement', models.CharField(blank=True, max_length=50)),
                ('direction_zip_code', models.CharField(max_length=10)),
                ('direction_neighborhood', models.CharField(max_length=255)),
                ('direction_city', models.CharField(max_length=255)),
                ('direction_state', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.groups')),
            ],
        ),
    ]
