# Generated by Django 5.1.1 on 2024-10-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clients_cnpj_alter_clients_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='direction_neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='direction_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='direction_street_complement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='direction_street_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
